// <auto-generated />
using System;
using Day4InClass.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Day4InClass.Data.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20201203200347_ProdCreate")]
    partial class ProdCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Day4InClass.Models.ToDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ToDos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2020, 12, 3, 12, 3, 46, 650, DateTimeKind.Local).AddTicks(6208),
                            Description = "Bake Cookies",
                            IsComplete = false,
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2020, 12, 3, 12, 3, 46, 658, DateTimeKind.Local).AddTicks(9653),
                            Description = "Eat the cookies",
                            IsComplete = false,
                            Priority = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2020, 12, 3, 12, 3, 46, 658, DateTimeKind.Local).AddTicks(9730),
                            Description = "Run around the block",
                            IsComplete = false,
                            Priority = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
